// Generated by Grafana k6 Studio (1.10.0) on 2026-01-27T13:21:41.780Z

import {group, sleep, check} from "k6";
import http from "k6/http";
import {getJSessionId, getVaadinPushId, getVaadinSecurityKey, getVaadinUiId} from "../../utils/vaadin-k6-helpers.js";

export const options = {
    stages: [
        { duration: '1m', target: 50 },
        { duration: '2m', target: 500 },
        { duration: '1m', target: 0 },
    ],
};

export default function () {
    let params;
    let resp;
    let url;

    group("Default group", function () {
        params = {
            headers: {
                "Proxy-Connection": `keep-alive`,
                "Upgrade-Insecure-Requests": `1`,
                Accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
                "Accept-Encoding": `gzip, deflate`,
                "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
            },
            cookies: {
	"JSESSIONID": `${jSessionId}`
},
        };

        const base_url = "${base_url}";

        url = http.url`${base_url}`;
        resp = http.request("GET", url, null, params);

        check(resp, {"status equals 200": (r) => r.status === 200});

        const jSessionId = getJSessionId(resp);

        params = {
            headers: {
                "Proxy-Connection": `keep-alive`,
                Accept: `*/*`,
                Referer: `${base_url}/`,
                "Accept-Encoding": `gzip, deflate`,
                "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
            },
            cookies: {
                "JSESSIONID": `${jSessionId}`
            }
        };

        url = http.url`${base_url}/?v-r=init&location=&query=&v-browserDetails=%7B%22v-sh%22%3A%221329%22%2C%22v-sw%22%3A%222056%22%2C%22v-wh%22%3A%221159%22%2C%22v-ww%22%3A%221200%22%2C%22v-bh%22%3A%221159%22%2C%22v-bw%22%3A%221200%22%2C%22v-curdate%22%3A%221769503654810%22%2C%22v-tzo%22%3A%22-60%22%2C%22v-dstd%22%3A%2260%22%2C%22v-rtzo%22%3A%22-60%22%2C%22v-dston%22%3A%22false%22%2C%22v-tzid%22%3A%22Europe%2FBerlin%22%2C%22v-wn%22%3A%22v-0.9920901482853236%22%2C%22v-td%22%3A%22false%22%2C%22v-pr%22%3A%222%22%2C%22v-np%22%3A%22MacIntel%22%2C%22v-cs%22%3A%22light%22%2C%22v-tn%22%3A%22lumo%22%7D`;
        resp = http.request("GET", url, null, params);

        check(resp, {"status equals 200": (r) => r.status === 200});

        const csrfToken = getVaadinSecurityKey(resp.body);
        const pushId = getVaadinPushId(resp.body);
        const uiId = getVaadinUiId(resp.body);

        params = {
            headers: {
                "Proxy-Connection": `keep-alive`,
                "Content-type": `application/json; charset=UTF-8`,
                Accept: `*/*`,
                Origin: `${base_url}`,
                Referer: `${base_url}/`,
                "Accept-Encoding": `gzip, deflate`,
                "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
            },
            cookies: {
                "JSESSIONID": `${jSessionId}`
            },
        };

        url = http.url`${base_url}/?v-r=uidl&v-uiId=${uiId}`;
        resp = http.request(
            "POST",
            url,
            `{"csrfToken":"${csrfToken}","rpc":[{"type":"event","node":1,"event":"ui-navigate","data":{"route":"","query":"","appShellTitle":"","historyState":{"idx":0},"trigger":""}}],"syncId":0,"clientId":0}`,
            params,
        );

        check(resp, {"status equals 200": (r) => r.status === 200});

        params = {
            headers: {
                "Proxy-Connection": `keep-alive`,
                "Content-type": `application/json; charset=UTF-8`,
                Accept: `*/*`,
                Origin: `${base_url}`,
                Referer: `${base_url}/`,
                "Accept-Encoding": `gzip, deflate`,
                "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
            },
            cookies: {
                "JSESSIONID": `${jSessionId}`
            },
        };

        url = http.url`${base_url}/?v-r=uidl&v-uiId=${uiId}`;
        resp = http.request(
            "POST",
            url,
            `{"csrfToken":"${csrfToken}","rpc":[{"type":"event","node":22,"event":"primary-section-changed","data":{}},{"type":"event","node":22,"event":"drawer-opened-changed","data":{}},{"type":"event","node":22,"event":"overlay-changed","data":{}},{"type":"event","node":17,"event":"collapsed-changed","data":{}},{"type":"event","node":16,"event":"expanded-changed","data":{}},{"type":"event","node":13,"event":"expanded-changed","data":{}},{"type":"mSync","node":22,"feature":1,"property":"drawerOpened","value":true},{"type":"mSync","node":22,"feature":1,"property":"overlay","value":false},{"type":"mSync","node":17,"feature":1,"property":"collapsed","value":false},{"type":"mSync","node":16,"feature":1,"property":"expanded","value":false},{"type":"mSync","node":13,"feature":1,"property":"expanded","value":false}],"syncId":1,"clientId":1}`,
            params,
        );

        check(resp, {"status equals 200": (r) => r.status === 200});

        params = {
            headers: {
                "Proxy-Connection": `keep-alive`,
                "Content-type": `application/json; charset=UTF-8`,
                Accept: `*/*`,
                Origin: `${base_url}`,
                Referer: `${base_url}/`,
                "Accept-Encoding": `gzip, deflate`,
                "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
            },
            cookies: {
                "JSESSIONID": `${jSessionId}`
            },
        };

        url = http.url`${base_url}/?v-r=uidl&v-uiId=${uiId}`;
        resp = http.request(
            "POST",
            url,
            `{"csrfToken":"${csrfToken}","rpc":[{"type":"event","node":16,"event":"expanded-changed","data":{}},{"type":"event","node":16,"event":"expanded-changed","data":{}}],"syncId":2,"clientId":2}`,
            params,
        );

        check(resp, {"status equals 200": (r) => r.status === 200});

        params = {
            headers: {
                "Proxy-Connection": `keep-alive`,
                "Content-type": `application/json; charset=UTF-8`,
                Accept: `*/*`,
                Origin: `${base_url}`,
                Referer: `${base_url}/`,
                "Accept-Encoding": `gzip, deflate`,
                "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
            },
            cookies: {
                "JSESSIONID": `${jSessionId}`
            },
        };

        url = http.url`${base_url}/?v-r=uidl&v-uiId=${uiId}`;
        resp = http.request(
            "POST",
            url,
            `{"csrfToken":"${csrfToken}","rpc":[{"type":"event","node":1,"event":"ui-navigate","data":{"route":"crud-example","query":"","appShellTitle":"","historyState":{"idx":0},"trigger":"client"}}],"syncId":3,"clientId":3}`,
            params,
        );

        check(resp, {"status equals 200": (r) => r.status === 200});

        params = {
            headers: {
                "Proxy-Connection": `keep-alive`,
                "Content-type": `application/json; charset=UTF-8`,
                Accept: `*/*`,
                Origin: `${base_url}`,
                Referer: `${base_url}/crud-example`,
                "Accept-Encoding": `gzip, deflate`,
                "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
            },
            cookies: {
                "JSESSIONID": `${jSessionId}`
            },
        };

        url = http.url`${base_url}/?v-r=uidl&v-uiId=${uiId}`;
        resp = http.request(
            "POST",
            url,
            `{"csrfToken":"${csrfToken}","rpc":[{"type":"event","node":35,"event":"value-changed","data":{}},{"type":"event","node":32,"event":"checked-changed","data":{}},{"type":"event","node":32,"event":"indeterminate-changed","data":{}},{"type":"publishedEventHandler","node":51,"templateEventMethodName":"confirmUpdate","templateEventMethodArgs":[0],"promise":0}],"syncId":4,"clientId":4}`,
            params,
        );

        check(resp, {"status equals 200": (r) => r.status === 200});

        params = {
            headers: {
                "Proxy-Connection": `keep-alive`,
                "Content-type": `application/json; charset=UTF-8`,
                Accept: `*/*`,
                Origin: `${base_url}`,
                Referer: `${base_url}/crud-example`,
                "Accept-Encoding": `gzip, deflate`,
                "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
            },
            cookies: {
                "JSESSIONID": `${jSessionId}`
            },
        };

        url = http.url`${base_url}/?v-r=uidl&v-uiId=${uiId}`;
        resp = http.request(
            "POST",
            url,
            `{"csrfToken":"${csrfToken}","rpc":[{"type":"event","node":13,"event":"expanded-changed","data":{}}],"syncId":5,"clientId":5}`,
            params,
        );

        check(resp, {"status equals 200": (r) => r.status === 200});

        params = {
            headers: {
                "Proxy-Connection": `keep-alive`,
                "Content-type": `application/json; charset=UTF-8`,
                Accept: `*/*`,
                Origin: `${base_url}`,
                Referer: `${base_url}/crud-example`,
                "Accept-Encoding": `gzip, deflate`,
                "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
            },
            cookies: {
                "JSESSIONID": `${jSessionId}`
            },
        };

        url = http.url`${base_url}/?v-r=uidl&v-uiId=${uiId}`;
        resp = http.request(
            "POST",
            url,
            `{"csrfToken":"${csrfToken}","rpc":[{"type":"publishedEventHandler","node":51,"templateEventMethodName":"select","templateEventMethodArgs":["1"],"promise":1},{"type":"publishedEventHandler","node":51,"templateEventMethodName":"setDetailsVisible","templateEventMethodArgs":["1"],"promise":2}],"syncId":6,"clientId":6}`,
            params,
        );

        check(resp, {"status equals 200": (r) => r.status === 200});

        params = {
            headers: {
                "Proxy-Connection": `keep-alive`,
                "Content-type": `application/json; charset=UTF-8`,
                Accept: `*/*`,
                Origin: `${base_url}`,
                Referer: `${base_url}/crud-example`,
                "Accept-Encoding": `gzip, deflate`,
                "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
            },
            cookies: {
                "JSESSIONID": `${jSessionId}`
            },
        };

        url = http.url`${base_url}/?v-r=uidl&v-uiId=${uiId}`;
        resp = http.request(
            "POST",
            url,
            `{"csrfToken":"${csrfToken}","rpc":[{"type":"event","node":35,"event":"value-changed","data":{}}],"syncId":7,"clientId":7}`,
            params,
        );

        check(resp, {"status equals 200": (r) => r.status === 200});

        params = {
            headers: {
                "Proxy-Connection": `keep-alive`,
                "Content-type": `application/json; charset=UTF-8`,
                Accept: `*/*`,
                Origin: `${base_url}`,
                Referer: `${base_url}/crud-example/1/edit`,
                "Accept-Encoding": `gzip, deflate`,
                "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
            },
            cookies: {
                "JSESSIONID": `${jSessionId}`
            },
        };

        url = http.url`${base_url}/?v-r=uidl&v-uiId=${uiId}`;
        resp = http.request(
            "POST",
            url,
            `{"csrfToken":"${csrfToken}","rpc":[{"type":"mSync","node":39,"feature":1,"property":"value","value":"Eula2"},{"type":"event","node":39,"event":"change","data":{}}],"syncId":8,"clientId":8}`,
            params,
        );

        check(resp, {"status equals 200": (r) => r.status === 200});

        params = {
            headers: {
                "Proxy-Connection": `keep-alive`,
                "Content-type": `application/json; charset=UTF-8`,
                Accept: `*/*`,
                Origin: `${base_url}`,
                Referer: `${base_url}/crud-example/1/edit`,
                "Accept-Encoding": `gzip, deflate`,
                "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
            },
            cookies: {
                "JSESSIONID": `${jSessionId}`
            },
        };

        url = http.url`${base_url}/?v-r=uidl&v-uiId=${uiId}`;
        resp = http.request(
            "POST",
            url,
            `{"csrfToken":"${csrfToken}","rpc":[{"type":"event","node":28,"event":"click","data":{"event.shiftKey":false,"event.metaKey":false,"event.detail":1,"event.ctrlKey":false,"event.clientX":1041,"event.clientY":1092,"event.altKey":false,"event.button":0,"event.screenY":1660,"event.screenX":4503}}],"syncId":9,"clientId":9}`,
            params,
        );

        check(resp, {"status equals 200": (r) => r.status === 200});

        params = {
            headers: {
                "Proxy-Connection": `keep-alive`,
                "Content-type": `application/json; charset=UTF-8`,
                Accept: `*/*`,
                Origin: `${base_url}`,
                Referer: `${base_url}/crud-example/1/edit`,
                "Accept-Encoding": `gzip, deflate`,
                "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
            },
            cookies: {
                "JSESSIONID": `${jSessionId}`
            },
        };

        url = http.url`${base_url}/?v-r=uidl&v-uiId=${uiId}`;
        resp = http.request(
            "POST",
            url,
            `{"csrfToken":"${csrfToken}","rpc":[{"type":"event","node":35,"event":"value-changed","data":{}},{"type":"event","node":55,"event":"opened-changed","data":{}},{"type":"publishedEventHandler","node":51,"templateEventMethodName":"setDetailsVisible","templateEventMethodArgs":[null],"promise":3},{"type":"publishedEventHandler","node":51,"templateEventMethodName":"confirmUpdate","templateEventMethodArgs":[1],"promise":4}],"syncId":10,"clientId":10}`,
            params,
        );

        check(resp, {"status equals 200": (r) => r.status === 200});

        params = {
            headers: {
                "Proxy-Connection": `keep-alive`,
                "Content-type": `application/json; charset=UTF-8`,
                Accept: `*/*`,
                Origin: `${base_url}`,
                Referer: `${base_url}/crud-example`,
                "Accept-Encoding": `gzip, deflate`,
                "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
            },
            cookies: {
                "JSESSIONID": `${jSessionId}`
            },
        };

        url = http.url`${base_url}/?v-r=uidl&v-uiId=${uiId}`;
        resp = http.request(
            "POST",
            url,
            `{"csrfToken":"${csrfToken}","rpc":[{"type":"event","node":13,"event":"expanded-changed","data":{}}],"syncId":11,"clientId":11}`,
            params,
        );

        check(resp, {"status equals 200": (r) => r.status === 200});

        params = {
            headers: {
                "Proxy-Connection": `keep-alive`,
                "Content-type": `application/json; charset=UTF-8`,
                Accept: `*/*`,
                Origin: `${base_url}`,
                Referer: `${base_url}/crud-example`,
                "Accept-Encoding": `gzip, deflate`,
                "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
            },
            cookies: {
                "JSESSIONID": `${jSessionId}`
            },
        };

        url = http.url`${base_url}/?v-r=uidl&v-uiId=${uiId}`;
        resp = http.request(
            "POST",
            url,
            `{"csrfToken":"${csrfToken}","rpc":[{"type":"publishedEventHandler","node":51,"templateEventMethodName":"select","templateEventMethodArgs":["7"],"promise":5},{"type":"publishedEventHandler","node":51,"templateEventMethodName":"setDetailsVisible","templateEventMethodArgs":["7"],"promise":6}],"syncId":12,"clientId":12}`,
            params,
        );

        check(resp, {"status equals 200": (r) => r.status === 200});

        params = {
            headers: {
                "Proxy-Connection": `keep-alive`,
                "Content-type": `application/json; charset=UTF-8`,
                Accept: `*/*`,
                Origin: `${base_url}`,
                Referer: `${base_url}/crud-example`,
                "Accept-Encoding": `gzip, deflate`,
                "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
            },
            cookies: {
                "JSESSIONID": `${jSessionId}`
            },
        };

        url = http.url`${base_url}/?v-r=uidl&v-uiId=${uiId}`;
        resp = http.request(
            "POST",
            url,
            `{"csrfToken":"${csrfToken}","rpc":[{"type":"event","node":35,"event":"value-changed","data":{}}],"syncId":13,"clientId":13}`,
            params,
        );

        check(resp, {"status equals 200": (r) => r.status === 200});

        params = {
            headers: {
                "Proxy-Connection": `keep-alive`,
                "Content-type": `application/json; charset=UTF-8`,
                Accept: `*/*`,
                Origin: `${base_url}`,
                Referer: `${base_url}/crud-example/7/edit`,
                "Accept-Encoding": `gzip, deflate`,
                "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
            },
            cookies: {
                "JSESSIONID": `${jSessionId}`
            },
        };

        url = http.url`${base_url}/?v-r=uidl&v-uiId=${uiId}`;
        resp = http.request(
            "POST",
            url,
            `{"csrfToken":"${csrfToken}","rpc":[{"type":"publishedEventHandler","node":51,"templateEventMethodName":"select","templateEventMethodArgs":["1"],"promise":7},{"type":"publishedEventHandler","node":51,"templateEventMethodName":"setDetailsVisible","templateEventMethodArgs":["1"],"promise":8}],"syncId":14,"clientId":14}`,
            params,
        );

        check(resp, {"status equals 200": (r) => r.status === 200});

        params = {
            headers: {
                "Proxy-Connection": `keep-alive`,
                "Content-type": `application/json; charset=UTF-8`,
                Accept: `*/*`,
                Origin: `${base_url}`,
                Referer: `${base_url}/crud-example/7/edit`,
                "Accept-Encoding": `gzip, deflate`,
                "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
            },
            cookies: {
                "JSESSIONID": `${jSessionId}`
            },
        };

        url = http.url`${base_url}/?v-r=uidl&v-uiId=${uiId}`;
        resp = http.request(
            "POST",
            url,
            `{"csrfToken":"${csrfToken}","rpc":[{"type":"event","node":35,"event":"value-changed","data":{}}],"syncId":15,"clientId":15}`,
            params,
        );

        check(resp, {"status equals 200": (r) => r.status === 200});

        params = {
            headers: {
                "Proxy-Connection": `keep-alive`,
                "Content-type": `application/json; charset=UTF-8`,
                Accept: `*/*`,
                Origin: `${base_url}`,
                Referer: `${base_url}/crud-example/1/edit`,
                "Accept-Encoding": `gzip, deflate`,
                "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
            },
            cookies: {
                "JSESSIONID": `${jSessionId}`
            },
        };

        url = http.url`${base_url}/?v-r=uidl&v-uiId=${uiId}`;
        resp = http.request(
            "POST",
            url,
            `{"csrfToken":"${csrfToken}","rpc":[{"type":"mSync","node":55,"feature":1,"property":"opened","value":false},{"type":"event","node":55,"event":"opened-changed","data":{}}],"syncId":16,"clientId":16}`,
            params,
        );

        check(resp, {"status equals 200": (r) => r.status === 200});

        params = {
            headers: {
                "Proxy-Connection": `keep-alive`,
                "Content-type": `application/json; charset=UTF-8`,
                Accept: `*/*`,
                Origin: `${base_url}`,
                Referer: `${base_url}/crud-example/1/edit`,
                "Accept-Encoding": `gzip, deflate`,
                "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
            },
            cookies: {
                "JSESSIONID": `${jSessionId}`
            },
        };

        url = http.url`${base_url}/?v-r=uidl&v-uiId=${uiId}`;
        resp = http.request(
            "POST",
            url,
            `{"csrfToken":"${csrfToken}","rpc":[{"type":"event","node":55,"event":"closed"}],"syncId":17,"clientId":17}`,
            params,
        );

        check(resp, {"status equals 200": (r) => r.status === 200});

        params = {
            headers: {
                "Proxy-Connection": `keep-alive`,
                "Content-type": `application/json; charset=UTF-8`,
                Accept: `*/*`,
                Origin: `${base_url}`,
                Referer: `${base_url}/crud-example/1/edit`,
                "Accept-Encoding": `gzip, deflate`,
                "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
            },
            cookies: {
                "JSESSIONID": `${jSessionId}`
            },
        };

        url = http.url`${base_url}/?v-r=uidl&v-uiId=${uiId}`;
        resp = http.request(
            "POST",
            url,
            `{"csrfToken":"${csrfToken}","rpc":[{"type":"mSync","node":39,"feature":1,"property":"value","value":"Eula"},{"type":"event","node":39,"event":"change","data":{}}],"syncId":18,"clientId":18}`,
            params,
        );

        check(resp, {"status equals 200": (r) => r.status === 200});

        params = {
            headers: {
                "Proxy-Connection": `keep-alive`,
                "Content-type": `application/json; charset=UTF-8`,
                Accept: `*/*`,
                Origin: `${base_url}`,
                Referer: `${base_url}/crud-example/1/edit`,
                "Accept-Encoding": `gzip, deflate`,
                "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
            },
            cookies: {
                "JSESSIONID": `${jSessionId}`
            },
        };

        url = http.url`${base_url}/?v-r=uidl&v-uiId=${uiId}`;
        resp = http.request(
            "POST",
            url,
            `{"csrfToken":"${csrfToken}","rpc":[{"type":"event","node":28,"event":"click","data":{"event.shiftKey":false,"event.metaKey":false,"event.detail":1,"event.ctrlKey":false,"event.clientX":1072,"event.clientY":1105,"event.altKey":false,"event.button":0,"event.screenY":1673,"event.screenX":4534}}],"syncId":19,"clientId":19}`,
            params,
        );

        check(resp, {"status equals 200": (r) => r.status === 200});

        params = {
            headers: {
                "Proxy-Connection": `keep-alive`,
                "Content-type": `application/json; charset=UTF-8`,
                Accept: `*/*`,
                Origin: `${base_url}`,
                Referer: `${base_url}/crud-example/1/edit`,
                "Accept-Encoding": `gzip, deflate`,
                "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
            },
            cookies: {
                "JSESSIONID": `${jSessionId}`
            },
        };

        url = http.url`${base_url}/?v-r=uidl&v-uiId=${uiId}`;
        resp = http.request(
            "POST",
            url,
            `{"csrfToken":"${csrfToken}","rpc":[{"type":"event","node":35,"event":"value-changed","data":{}},{"type":"event","node":56,"event":"opened-changed","data":{}},{"type":"publishedEventHandler","node":51,"templateEventMethodName":"setDetailsVisible","templateEventMethodArgs":[null],"promise":9},{"type":"publishedEventHandler","node":51,"templateEventMethodName":"confirmUpdate","templateEventMethodArgs":[2],"promise":10}],"syncId":20,"clientId":20}`,
            params,
        );

        check(resp, {"status equals 200": (r) => r.status === 200});

        params = {
            headers: {
                "Proxy-Connection": `keep-alive`,
                "Content-type": `application/json; charset=UTF-8`,
                Accept: `*/*`,
                Origin: `${base_url}`,
                Referer: `${base_url}/crud-example`,
                "Accept-Encoding": `gzip, deflate`,
                "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
            },
            cookies: {
                "JSESSIONID": `${jSessionId}`
            },
        };

        url = http.url`${base_url}/?v-r=uidl&v-uiId=${uiId}`;
        resp = http.request(
            "POST",
            url,
            `{"csrfToken":"${csrfToken}","rpc":[{"type":"event","node":13,"event":"expanded-changed","data":{}}],"syncId":21,"clientId":21}`,
            params,
        );

        check(resp, {"status equals 200": (r) => r.status === 200});

        params = {
            headers: {
                "Proxy-Connection": `keep-alive`,
                "Content-Type": `text/plain;charset=UTF-8`,
                Accept: `*/*`,
                Origin: `${base_url}`,
                Referer: `${base_url}/crud-example`,
                "Accept-Encoding": `gzip, deflate`,
                "Accept-Language": `en-GB,en-US;q=0.9,en;q=0.8`,
            },
            cookies: {
                "JSESSIONID": `${jSessionId}`
            },
        };

        url = http.url`${base_url}/?v-r=uidl&v-uiId=${uiId}`;
        resp = http.request(
            "POST",
            url,
            `{"csrfToken":"${csrfToken}","rpc":[],"UNLOAD":true}`,
            params,
        );

        check(resp, {"status equals 200": (r) => r.status === 200});
    });
    sleep(Math.random() * (2 - 0.5) + 0.5);
}
